apiVersion: v2
name: poddeck-agent
description: PodDeck Agent - deployed into each managed Kubernetes cluster
icon: https://raw.githubusercontent.com/poddeck/poddeck-deployment/main/assets/icon.png
type: application
version: 1.0.0
appVersion: "1.0.0"
