apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poddeck-agent.fullname" . }}-helm-cache
  labels:
    {{- include "poddeck-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.helm.cache.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poddeck-agent.fullname" . }}-helm-config
  labels:
    {{- include "poddeck-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.helm.config.size }}
