{{- if .Values.telegraf.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.telegraf.namespace }}
  labels:
    {{- include "poddeck-agent.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: {{ .Values.telegraf.namespace }}
  labels:
    {{- include "poddeck-agent.labels" . | nindent 4 }}
data:
  telegraf.conf: |
    [agent]
      interval = "1s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "1s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = ""
      hostname = ""

    [[outputs.prometheus_client]]
      listen = ":{{ .Values.telegraf.port }}"
      path = "/metrics"
      expiration_interval = "60s"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false

    [[inputs.mem]]
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs"]
    [[inputs.net]]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: {{ .Values.telegraf.namespace }}
  labels:
    app: telegraf
    {{- include "poddeck-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 250m
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
          ports:
            - containerPort: {{ .Values.telegraf.port }}
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.telegraf.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.telegraf.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      terminationGracePeriodSeconds: 30
{{- end }}
