apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poddeck.fullname" . }}-core
  labels:
    {{- include "poddeck.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-key: {{ .Values.core.auth.authenticationKey | default (randAlphaNum 32) | quote }}
  refresh-key: {{ .Values.core.auth.refreshKey | default (randAlphaNum 32) | quote }}
  {{- if .Values.postgresql.enabled }}
  db-password: {{ .Values.postgresql.auth.password | quote }}
  {{- else }}
  db-password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
