apiVersion: v1
kind: Service
metadata:
  name: {{ include "poddeck.fullname" . }}-panel
  labels:
    {{- include "poddeck.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    app.kubernetes.io/name: poddeck
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: panel
