name: Lint

on:
  push:
  pull_request:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint -c .yamllint.yml .

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add Bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Build chart dependencies
        run: helm dependency build charts/poddeck

      - name: Lint control plane chart
        run: helm lint charts/poddeck

      - name: Lint agent chart
        run: helm lint charts/poddeck-agent --set core.hostname=test --set cluster.id=test --set cluster.key=test
